ollama_pull_models:
  - "aya-expanse:8b-q4_K_M"
  - "gemma2:9b-instruct-q4_K_M"
  - "granite3.1-dense:8b-instruct-q4_K_M"
  - "marco-o1:7b-q4_K_M"
  - "mistral:7b-instruct-q4_K_M"
  - "olmo2:7b-1124-instruct-q4_K_M"
  - "phi4:14b-q4_K_M"
  - "tulu3:8b-q4_K_M"

ollama_rename_prefix_models:
  - "CognitiveComputations/"





